name: Run the qodo-cover-pr action (Python)

on:
  pull_request:
    branches:
      - main
    types:
      - opened  # Trigger only when a pull request is opened

permissions:
  pull-requests: write  # Allows commenting on pull requests
  contents: write  # Allows reading and writing files

jobs:
  run-qodo-cover-pr-python:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-dev python3-pip
          python3 --version

      - name: Install app dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r templated_tests/python_fastapi/requirements.txt

      - name: Qodo Cover
        uses: qodo-ai/qodo-ci/.github/actions/qodo-cover-pr@v0.1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_language: python
          project_root: templated_tests/python_fastapi
          code_coverage_report_path: templated_tests/python_fastapi/coverage.xml
          test_command: "pytest --cov=. --cov-report=xml --cov-report=term"
          model: gpt-4o
          desired_coverage: 70
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}